version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test-and-release:
    jobs:
      - test
      - release:
          requires:
            - test
  test:
    jobs:
      - test

jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn
      - run: yarn build
      - run: yarn semantic-release
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn
      - run: yarn test
