version: 2.1

orbs:
  node: circleci/node@4.7

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16.13.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    <<: *defaults
    steps:
      - run:
          name: Run Tests
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  release:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn
      - run: yarn build
      - run: yarn semantic-release
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish the package
          command: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - build